spring.application.name=MobileCare
spring.datasource.url=jdbc:mysql://localhost:3306/mobilecare?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Gagan@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
